apiVersion: v1
kind: Pod
metadata:
  name: kafka-loader
  namespace: kafka
spec:
  restartPolicy: Always
  containers:
    - name: loader
      image: apache/kafka:4.1.1
      command: ["bash", "-lc", "sleep infinity"]
      volumeMounts:
        - name: bench-scripts
          mountPath: /opt/bench
  volumes:
    - name: bench-scripts
      configMap:
        name: bench-scripts
        defaultMode: 0755
