apiVersion: v1
kind: ConfigMap
metadata:
  name: topic-autocreate-config
  namespace: kafka
data:
  REPEATS_PER_POD: "5"
  MESSAGE_COUNT: "1"
  SLEEP_BETWEEN: "1"
  WAIT_FOR_RELEASE: "1"
  ASYNC_EVENT: "cpu"
  ASYNC_DURATION: "10"
  SLEEP_AFTER_SEND: "10"
